po4a infrastructure and translations for manpages.
Gbp-Pq: manpage-translations.patch.

diff --git a/man/Makefile.l10n b/man/Makefile.l10n
--- a/man/Makefile.l10n
+++ b/man/Makefile.l10n
@@ -1,9 +1,9 @@
 #
-# "$Id: Makefile 9177 2010-06-22 21:21:37Z mike $"
+# "$Id: $"
 #
-#   Man page makefile for CUPS.
+#   Man page makefile for the Common UNIX Printing System (CUPS).
 #
-#   Copyright 2007-2010 by Apple Inc.
+#   Copyright 2007 by Apple Inc.
 #   Copyright 1993-2006 by Easy Software Products.
 #
 #   These coded instructions, statements, and computer programs are the
@@ -13,7 +13,7 @@
 #   file is missing or damaged, see the license at "http://www.cups.org/".
 #
 
-include ../Makedefs
+include ../../Makedefs
 
 
 #
@@ -24,33 +24,24 @@ MAN1	=	cancel.$(MAN1EXT) \
 		cups-config.$(MAN1EXT) \
 		cupstestdsc.$(MAN1EXT) \
 		cupstestppd.$(MAN1EXT) \
-		ipptool.$(MAN1EXT) \
 		lp.$(MAN1EXT) \
 		lpoptions.$(MAN1EXT) \
 		lppasswd.$(MAN1EXT) \
 		lpq.$(MAN1EXT) \
 		lprm.$(MAN1EXT) \
 		lpr.$(MAN1EXT) \
-		lpstat.$(MAN1EXT) \
-		ppdc.$(MAN1EXT) \
-		ppdhtml.$(MAN1EXT) \
-		ppdi.$(MAN1EXT) \
-		ppdmerge.$(MAN1EXT) \
-		ppdpo.$(MAN1EXT)
+		lpstat.$(MAN1EXT)
 MAN5	=	classes.conf.$(MAN5EXT) \
 		client.conf.$(MAN5EXT) \
 		cups-snmp.conf.$(MAN5EXT) \
 		cupsd.conf.$(MAN5EXT) \
-		ipptoolfile.$(MAN5EXT) \
 		mailto.conf.$(MAN5EXT) \
 		mime.convs.$(MAN5EXT) \
 		mime.types.$(MAN5EXT) \
-		ppdcfile.$(MAN5EXT) \
 		printers.conf.$(MAN5EXT) \
 		subscriptions.conf.$(MAN5EXT)
 MAN7	=	backend.$(MAN7EXT) \
-		filter.$(MAN7EXT) \
-		notifier.$(MAN7EXT)
+		filter.$(MAN7EXT)
 MAN8	=	cupsaccept.$(MAN8EXT) \
 		cupsaddsmb.$(MAN8EXT) \
 		cupsctl.$(MAN8EXT) \
@@ -66,58 +57,44 @@ MAN8	=	cupsaccept.$(MAN8EXT) \
 		lpmove.$(MAN8EXT) \
 		lpc.$(MAN8EXT)
 
-LANGUAGES=de fr
 
 #
 # Make everything...
 #
 
-all:	$(MAN1) $(MAN5) $(MAN7) $(MAN8) html translations
+all:	manpages.gz html
 
-translations:
-	# Update the translations and build the translated material
-	po4a --previous po4a/cups.cfg
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang; done
-
-
-#
-# Make library targets...
-#
-
-libs:
-
-
-#
-# Make unit tests...
-#
-
-unittests:
-
+# Prepare all the existing manpages, and compress them.
+# But do not fail if a manpage was not generated.
+manpages.gz: manpages.gz-stamp
+manpages.gz-stamp:
+	for file in $(MAN1) $(MAN5) $(MAN7) $(MAN8); do \
+		$(MAKE) $$file || true; \
+	done
+	touch $@
 
 #
 # Clean all config and object files...
 #
 
 clean:
-	$(RM) mantohtml mantohtml.o
 	$(RM) $(MAN1) $(MAN5) $(MAN7) $(MAN8)
 	for file in $(MAN1); do \
-		$(RM) ../doc/help/man-`basename $$file .$(MAN1EXT)`.html; \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN1EXT)`.$(LANGUAGE).html; \
 	done
 	for file in $(MAN5); do \
-		$(RM) ../doc/help/man-`basename $$file .$(MAN5EXT)`.html; \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN5EXT)`.$(LANGUAGE).html; \
 	done
 	for file in $(MAN7); do \
-		$(RM) ../doc/help/man-`basename $$file .$(MAN7EXT)`.html; \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN7EXT)`.$(LANGUAGE).html; \
 	done
 	for file in $(MAN8); do \
-		$(RM) ../doc/help/man-`basename $$file .$(MAN8EXT)`.html; \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN8EXT)`.$(LANGUAGE).html; \
 	done
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang clean; done
-	# Make sure the PO files are updated and remove generated
-	# translations.
-	po4a --previous --rm-translations po4a/cups.cfg
-	$(RM) po4a/po/cups.pot
+	for file in *.man.in; do \
+		$(RM) `basename $$file .in`; \
+	done
+	$(RM) manpages.gz-stamp
 
 
 #
@@ -128,65 +105,45 @@ depend:
 
 
 #
-# Install all targets...
+# Install files...
 #
 
-install:	all install-data install-headers install-libs install-exec
+MANDIR := $(MANDIR)/$(LANGUAGE)
+AMANDIR := $(AMANDIR)/$(LANGUAGE)
 
-
-#
-# Install data files...
-#
-
-install-data: all
+install:	all
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man1
-	for file in $(MAN1); do \
+	for file in $(wildcard $(MAN1)); do \
 		echo Installing $$file in $(MANDIR)/man1...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man1; \
 	done
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man5
-	for file in $(MAN5); do \
+	for file in $(wildcard $(MAN5)); do \
 		echo Installing $$file in $(MANDIR)/man5...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man5; \
 	done
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man7
-	for file in $(MAN7); do \
+	for file in $(wildcard $(MAN7)); do \
 		echo Installing $$file in $(MANDIR)/man7...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man7; \
 	done
 	$(INSTALL_DIR) -m 755 $(AMANDIR)/man$(MAN8DIR)
-	for file in $(MAN8); do \
+	for file in $(wildcard $(MAN8)); do \
 		echo Installing $$file in $(AMANDIR)/man$(MAN8DIR)...; \
 		$(INSTALL_MAN) $$file $(AMANDIR)/man$(MAN8DIR); \
 	done
-	for file in accept cupsreject reject; do \
-		$(RM) $(AMANDIR)/man$(MAN8DIR)/$$file.$(MAN8EXT); \
-		$(LN) cupsaccept.$(MAN8EXT) $(AMANDIR)/man$(MAN8DIR)/$$file.$(MAN8EXT); \
-	done
-	$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT)
-	$(LN) cupsenable.$(MAN8EXT) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT)
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang install; done
-
-
-#
-# Install programs...
-#
-
-install-exec:
-
-
-#
-# Install headers...
-#
-
-install-headers:
-
-
-#
-# Install libraries...
-#
-
-install-libs:
+	if [ -f cupsreject.$(MAN8EXT) ]; then \
+		$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsreject.$(MAN8EXT); \
+	fi
+	if [ -f cupsaccept.$(MAN8EXT) ]; then \
+		$(LN) cupsaccept.$(MAN8EXT) $(AMANDIR)/man$(MAN8DIR)/cupsreject.$(MAN8EXT); \
+	fi
+	if [ -f cupsdisable.$(MAN8EXT) ]; then \
+		$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT); \
+	fi
+	if [ -f cupsenable.$(MAN8EXT) ]; then \
+		$(LN) cupsenable.$(MAN8EXT) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT); \
+	fi
 
 
 #
@@ -209,41 +166,44 @@ uninstall:
 	for file in $(MAN8); do \
 		$(RM) $(AMANDIR)/man$(MAN8DIR)/$$file; \
 	done
-	$(RM) $(AMANDIR)/man$(MAN8DIR)/accept.$(MAN8EXT)
 	$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsreject.$(MAN8EXT)
-	$(RM) $(AMANDIR)/man$(MAN8DIR)/reject.$(MAN8EXT)
 	$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT)
 	-$(RMDIR) $(AMANDIR)/man$(MAN8DIR)
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang uninstall; done
 
 
 #
 # Make html versions of man pages...
 #
 
-html:	$(MAN1) $(MAN5) $(MAN7) $(MAN8) mantohtml
+MANTOHTML = ../mantohtml
+html:	manpages.gz $(MANTOHTML)
 	echo Converting man pages to HTML...
-	for file in $(MAN1); do \
+	for file in $(wildcard $(MAN1)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN1EXT)`.man >../doc/help/man-`basename $$file .$(MAN1EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN1EXT)`.man >../../doc/help/man-`basename $$file .$(MAN1EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN5); do \
+	for file in $(wildcard $(MAN5)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN5EXT)`.man >../doc/help/man-`basename $$file .$(MAN5EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN5EXT)`.man >../../doc/help/man-`basename $$file .$(MAN5EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN7); do \
+	for file in $(wildcard $(MAN7)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN7EXT)`.man >../doc/help/man-`basename $$file .$(MAN7EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN7EXT)`.man >../../doc/help/man-`basename $$file .$(MAN7EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN8); do \
+	for file in $(wildcard $(MAN8)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN8EXT)`.man >../doc/help/man-`basename $$file .$(MAN8EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN8EXT)`.man >../../doc/help/man-`basename $$file .$(MAN8EXT)`.$(LANGUAGE).html; \
 	done
 
-mantohtml:	mantohtml.o
-	$(CC) $(ARCHFLAGS) $(LDFLAGS) -o $@ mantohtml.o
+.SUFFIXES: .man.in .man
+# Keep the generated .man because they are needed for the html rule
+.PRECIOUS: %.man
 
+.man.in.man:
+	sed -e 's:@CUPS_DATADIR@:$(DATADIR):' \
+	    -e 's:@CUPS_SERVERROOT@:$(SERVERROOT):' \
+	    -e 's:@CUPS_SERVERBIN@:$(SERVERBIN):' $< > $@
 
 #
-# End of "$Id: Makefile 9177 2010-06-22 21:21:37Z mike $".
+# End of "$Id: $".
 #
