po4a infrastructure and translations for manpages.
Gbp-Pq: manpage-translations.patch.

diff --git a/man/Makefile.l10n b/man/Makefile.l10n
--- a/man/Makefile.l10n
+++ b/man/Makefile.l10n
@@ -1,13 +1,17 @@
 #
 # Man page makefile for CUPS.
 #
-# Copyright 2007-2018 by Apple Inc.
+# Copyright 2007-2017 by Apple Inc.
 # Copyright 1993-2006 by Easy Software Products.
 #
-# Licensed under Apache License v2.0.  See the file "LICENSE" for more information.
+# These coded instructions, statements, and computer programs are the
+# property of Apple Inc. and are protected by Federal copyright
+# law.  Distribution and use rights are outlined in the file "LICENSE.txt"
+# which should have been included with this file.  If this file is
+# missing or damaged, see the license at "http://www.cups.org/".
 #
 
-include ../Makedefs
+include ../../Makedefs
 
 
 #
@@ -60,33 +64,20 @@ MAN8	=	cupsaccept.$(MAN8EXT) \
 		lpmove.$(MAN8EXT) \
 		lpc.$(MAN8EXT)
 
-LANGUAGES=de fr
-
 #
 # Make everything...
 #
 
-all:	$(MAN1) $(MAN5) $(MAN7) $(MAN8) translations
+all:	manpages.gz html
 
-translations:
-	# Update the translations and build the translated material
-	po4a --previous ../debian/manpage-po4a/cups.cfg
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang; done
-
-
-#
-# Make library targets...
-#
-
-libs:
-
-
-#
-# Make unit tests...
-#
-
-unittests:
-
+# Prepare all the existing manpages, and compress them.
+# But do not fail if a manpage was not generated.
+manpages.gz: manpages.gz-stamp
+manpages.gz-stamp:
+	for file in $(MAN1) $(MAN5) $(MAN7) $(MAN8); do \
+		$(MAKE) $$file || true; \
+	done
+	touch $@
 
 #
 # Clean all config and object files...
@@ -95,11 +86,22 @@ unittests:
 clean:
 	$(RM) mantohtml mantohtml.o
 	$(RM) $(MAN1) $(MAN5) $(MAN7) $(MAN8)
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang clean; done
-	# Make sure the PO files are updated and remove generated
-	# translations.
-	po4a --previous --rm-translations ../debian/manpage-po4a/cups.cfg
-	$(RM) ../debian/manpage-po4a/po/cups.pot
+	for file in $(MAN1); do \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN1EXT)`.$(LANGUAGE).html; \
+	done
+	for file in $(MAN5); do \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN5EXT)`.$(LANGUAGE).html; \
+	done
+	for file in $(MAN7); do \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN7EXT)`.$(LANGUAGE).html; \
+	done
+	for file in $(MAN8); do \
+		$(RM) ../../doc/help/man-`basename $$file .$(MAN8EXT)`.$(LANGUAGE).html; \
+	done
+	for file in *.man.in; do \
+		$(RM) `basename $$file .in`; \
+	done
+	$(RM) manpages.gz-stamp
 
 
 #
@@ -113,6 +115,9 @@ depend:
 # Install all targets...
 #
 
+MANDIR := $(MANDIR)/$(LANGUAGE)
+AMANDIR := $(AMANDIR)/$(LANGUAGE)
+
 install:	all install-data install-headers install-libs install-exec
 
 
@@ -122,22 +127,22 @@ install:	all install-data install-headers install-libs install-exec
 
 install-data: all
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man1
-	for file in $(MAN1); do \
+	for file in $(wildcard $(MAN1)); do \
 		echo Installing $$file in $(MANDIR)/man1...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man1; \
 	done
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man5
-	for file in $(MAN5); do \
+	for file in $(wildcard $(MAN5)); do \
 		echo Installing $$file in $(MANDIR)/man5...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man5; \
 	done
 	$(INSTALL_DIR) -m 755 $(MANDIR)/man7
-	for file in $(MAN7); do \
+	for file in $(wildcard $(MAN7)); do \
 		echo Installing $$file in $(MANDIR)/man7...; \
 		$(INSTALL_MAN) $$file $(MANDIR)/man7; \
 	done
 	$(INSTALL_DIR) -m 755 $(AMANDIR)/man$(MAN8DIR)
-	for file in $(MAN8); do \
+	for file in $(wildcard $(MAN8)); do \
 		echo Installing $$file in $(AMANDIR)/man$(MAN8DIR)...; \
 		$(INSTALL_MAN) $$file $(AMANDIR)/man$(MAN8DIR); \
 	done
@@ -151,7 +156,6 @@ install-data: all
 		$(RM) $(AMANDIR)/man$(MAN8DIR)/$$file.$(MAN8EXT); \
 		$(LN) cupsd-helper.$(MAN8EXT) $(AMANDIR)/man$(MAN8DIR)/$$file.$(MAN8EXT); \
 	done
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang install; done
 
 
 #
@@ -200,38 +204,41 @@ uninstall:
 	$(RM) $(AMANDIR)/man$(MAN8DIR)/reject.$(MAN8EXT)
 	$(RM) $(AMANDIR)/man$(MAN8DIR)/cupsdisable.$(MAN8EXT)
 	-$(RMDIR) $(AMANDIR)/man$(MAN8DIR)
-	for lang in $(LANGUAGES); do $(MAKE) -C $$lang uninstall; done
-
-
-#
-# Local programs (not built when cross-compiling...)
-#
-
-local:	html
 
 
 #
 # Make html versions of man pages...
 #
 
-html:	$(MAN1) $(MAN5) $(MAN7) $(MAN8) mantohtml
+MANTOHTML = ../mantohtml
+html:	manpages.gz $(MANTOHTML)
 	echo Converting man pages to HTML...
-	for file in $(MAN1); do \
+	for file in $(wildcard $(MAN1)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN1EXT)`.man >../doc/help/man-`basename $$file .$(MAN1EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN1EXT)`.man >../../doc/help/man-`basename $$file .$(MAN1EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN5); do \
+	for file in $(wildcard $(MAN5)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN5EXT)`.man >../doc/help/man-`basename $$file .$(MAN5EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN5EXT)`.man >../../doc/help/man-`basename $$file .$(MAN5EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN7); do \
+	for file in $(wildcard $(MAN7)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN7EXT)`.man >../doc/help/man-`basename $$file .$(MAN7EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN7EXT)`.man >../../doc/help/man-`basename $$file .$(MAN7EXT)`.$(LANGUAGE).html; \
 	done
-	for file in $(MAN8); do \
+	for file in $(wildcard $(MAN8)); do \
 		echo "    $$file..."; \
-		./mantohtml `basename $$file .$(MAN8EXT)`.man >../doc/help/man-`basename $$file .$(MAN8EXT)`.html; \
+		$(MANTOHTML) `basename $$file .$(MAN8EXT)`.man >../../doc/help/man-`basename $$file .$(MAN8EXT)`.$(LANGUAGE).html; \
 	done
 
-mantohtml:	mantohtml.c
+$(MANTOHTML): $(MANTOHTML).c
 	$(CC_FOR_BUILD) -o $@ $<
+
+.SUFFIXES: .man.in .man
+# Keep the generated .man because they are needed for the html rule
+.PRECIOUS: %.man
+
+.man.in.man:
+	sed -e 's:@CUPS_DATADIR@:$(DATADIR):' \
+	    -e 's:@CUPS_SERVERROOT@:$(SERVERROOT):' \
+	    -e 's:@CUPS_SERVERBIN@:$(SERVERBIN):' $< > $@
+
