1.3.10-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -799,6 +799,8 @@ CUPS_SNMP_ADDRESS
 CUPS_SNMP_COMMUNITY
 DEFAULT_IPP_PORT
 PAP
+CUPS_PDFTOPS
+CUPS_GHOSTSCRIPT
 PDFTOPS
 JAVA
 PERL
@@ -1428,6 +1430,7 @@ Optional Features:
   --enable-use-network-default
                           enable UseNetworkDefault by default, default=auto
   --enable-raw-printing   enable raw printing by default, default=auto
+  --enable-pap            build with AppleTalk support, default=auto
   --enable-pdftops        build pdftops filter, default=auto
 
 Optional Packages:
@@ -1481,6 +1484,7 @@ Optional Packages:
   --with-snmp-address     set SNMP query address, default=auto
   --with-snmp-community   set SNMP community, default=public
   --with-ipp-port         set default port number for IPP
+  --with-pdftops          set pdftops filter (gs,pdftops,none), default=pdftops
   --with-java             set Java interpreter for web interfaces
   --with-perl             set Perl interpreter for web interfaces
   --with-php              set PHP interpreter for web interfaces
@@ -1945,7 +1949,7 @@ esac
 ac_config_headers="$ac_config_headers config.h"
 
 
-CUPS_VERSION=1.3.9
+CUPS_VERSION=1.3.10
 CUPS_REVISION=
 
 
@@ -8998,7 +9002,7 @@ _ACEOF
 
 			if test "x$default_adminkey" != xdefault; then
 				CUPS_SYSTEM_AUTHKEY="SystemGroupAuthKey $default_adminkey"
-			elif grep -q system.print.operator /etc/authorization; then
+			elif grep -q system.print.admin /etc/authorization; then
 				CUPS_SYSTEM_AUTHKEY="SystemGroupAuthKey system.print.admin"
 			else
 				CUPS_SYSTEM_AUTHKEY="SystemGroupAuthKey system.preferences"
@@ -9371,7 +9375,7 @@ if test x$rcdir = x; then
 			;;
 
 	esac
-else
+elif test "x$rcdir" != xno; then
 	if test "x$rclevels" = x; then
 		INITDDIR="$rcdir"
 	else
@@ -9401,6 +9405,8 @@ if test "x$XINETD" = x -a ! -x /sbin/launchd; then
 			break
 		fi
 	done
+elif test "x$XINETD" = xno; then
+	XINETD=""
 fi
 
 
@@ -9654,14 +9660,6 @@ fi
 
 
 case "$uname" in
-	*BSD* | Darwin*)
-		# *BSD
-		MAN1EXT=1
-		MAN5EXT=5
-		MAN7EXT=7
-		MAN8EXT=8
-		MAN8DIR=8
-		;;
 	IRIX*)
 		# SGI IRIX
 		MAN1EXT=1
@@ -9678,8 +9676,8 @@ case "$uname" in
 		MAN8EXT=1m
 		MAN8DIR=1m
 		;;
-	Linux* | GNU*)
-		# Linux and GNU Hurd
+	Linux* | GNU* | Darwin*)
+		# Linux, GNU Hurd, and Mac OS X
 		MAN1EXT=1.gz
 		MAN5EXT=5.gz
 		MAN7EXT=7.gz
@@ -18370,10 +18368,145 @@ _ACEOF
 
 # Currently the PAP backend is only supported on MacOS X with the AppleTalk
 # SDK installed...
+# Check whether --enable-pap was given.
+if test "${enable_pap+set}" = set; then
+  enableval=$enable_pap;
+fi
+
+
 PAP=""
-if test $uname = Darwin; then
-	PAP="pap"
-	if test "${ac_cv_header_AppleTalk_at_proto_h+set}" = set; then
+
+
+if test x$enable_pap != xno -a $uname = Darwin; then
+	if test "${ac_cv_header_netat_appletalk_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for netat/appletalk.h" >&5
+echo $ECHO_N "checking for netat/appletalk.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_netat_appletalk_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_netat_appletalk_h" >&5
+echo "${ECHO_T}$ac_cv_header_netat_appletalk_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking netat/appletalk.h usability" >&5
+echo $ECHO_N "checking netat/appletalk.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <netat/appletalk.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking netat/appletalk.h presence" >&5
+echo $ECHO_N "checking netat/appletalk.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netat/appletalk.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: netat/appletalk.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: netat/appletalk.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: netat/appletalk.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: netat/appletalk.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: netat/appletalk.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: netat/appletalk.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netat/appletalk.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netat/appletalk.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: netat/appletalk.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for netat/appletalk.h" >&5
+echo $ECHO_N "checking for netat/appletalk.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_netat_appletalk_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_netat_appletalk_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_netat_appletalk_h" >&5
+echo "${ECHO_T}$ac_cv_header_netat_appletalk_h" >&6; }
+
+fi
+if test $ac_cv_header_netat_appletalk_h = yes; then
+
+		PAP="pap"
+		if test "${ac_cv_header_AppleTalk_at_proto_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for AppleTalk/at_proto.h" >&5
 echo $ECHO_N "checking for AppleTalk/at_proto.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_AppleTalk_at_proto_h+set}" = set; then
@@ -18503,6 +18636,7 @@ fi
 fi
 
 
+fi
 
 
 
@@ -18512,20 +18646,239 @@ if test "${enable_pdftops+set}" = set; then
 fi
 
 
-PDFTOPS=""
-
-if test "x$enable_pdftops" != xno; then
-	{ echo "$as_me:$LINENO: checking whether to build pdftops filter" >&5
-echo $ECHO_N "checking whether to build pdftops filter... $ECHO_C" >&6; }
-	if test "x$enable_pdftops" = xyes -o $uname != Darwin; then
-		PDFTOPS="pdftops"
-		{ echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-	else
-		{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-	fi
+# Check whether --with-pdftops was given.
+if test "${with_pdftops+set}" = set; then
+  withval=$with_pdftops;
 fi
+
+
+if test "x$enable_pdftops" = xno -a "x$with_pdftops" = x; then
+	with_pdftops=no
+fi
+
+PDFTOPS=""
+CUPS_PDFTOPS=""
+CUPS_GHOSTSCRIPT=""
+
+case "x$with_pdftops" in
+	x) # Default/auto
+	if test $uname != Darwin; then
+		# Extract the first word of "pdftops", so it can be a program name with args.
+set dummy pdftops; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_CUPS_PDFTOPS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CUPS_PDFTOPS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CUPS_PDFTOPS="$CUPS_PDFTOPS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_CUPS_PDFTOPS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+CUPS_PDFTOPS=$ac_cv_path_CUPS_PDFTOPS
+if test -n "$CUPS_PDFTOPS"; then
+  { echo "$as_me:$LINENO: result: $CUPS_PDFTOPS" >&5
+echo "${ECHO_T}$CUPS_PDFTOPS" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+		if test "x$CUPS_PDFTOPS" != x; then
+			cat >>confdefs.h <<\_ACEOF
+#define HAVE_PDFTOPS 1
+_ACEOF
+
+			PDFTOPS="pdftops"
+		else
+			# Extract the first word of "gs", so it can be a program name with args.
+set dummy gs; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_CUPS_GHOSTSCRIPT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CUPS_GHOSTSCRIPT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CUPS_GHOSTSCRIPT="$CUPS_GHOSTSCRIPT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_CUPS_GHOSTSCRIPT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+CUPS_GHOSTSCRIPT=$ac_cv_path_CUPS_GHOSTSCRIPT
+if test -n "$CUPS_GHOSTSCRIPT"; then
+  { echo "$as_me:$LINENO: result: $CUPS_GHOSTSCRIPT" >&5
+echo "${ECHO_T}$CUPS_GHOSTSCRIPT" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+			if test "x$CUPS_GHOSTSCRIPT" != x; then
+				cat >>confdefs.h <<\_ACEOF
+#define HAVE_GHOSTSCRIPT 1
+_ACEOF
+
+				PDFTOPS="pdftops"
+			fi
+		fi
+	fi
+	;;
+
+	xgs)
+	# Extract the first word of "gs", so it can be a program name with args.
+set dummy gs; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_CUPS_GHOSTSCRIPT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CUPS_GHOSTSCRIPT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CUPS_GHOSTSCRIPT="$CUPS_GHOSTSCRIPT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_CUPS_GHOSTSCRIPT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+CUPS_GHOSTSCRIPT=$ac_cv_path_CUPS_GHOSTSCRIPT
+if test -n "$CUPS_GHOSTSCRIPT"; then
+  { echo "$as_me:$LINENO: result: $CUPS_GHOSTSCRIPT" >&5
+echo "${ECHO_T}$CUPS_GHOSTSCRIPT" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+	if test "x$CUPS_GHOSTSCRIPT" != x; then
+		cat >>confdefs.h <<\_ACEOF
+#define HAVE_GHOSTSCRIPT 1
+_ACEOF
+
+		PDFTOPS="pdftops"
+	else
+		{ { echo "$as_me:$LINENO: error: Unable to find gs program!" >&5
+echo "$as_me: error: Unable to find gs program!" >&2;}
+   { (exit 1); exit 1; }; }
+		exit 1
+	fi
+	;;
+
+	xpdftops)
+	# Extract the first word of "pdftops", so it can be a program name with args.
+set dummy pdftops; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_CUPS_PDFTOPS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CUPS_PDFTOPS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CUPS_PDFTOPS="$CUPS_PDFTOPS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_CUPS_PDFTOPS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+CUPS_PDFTOPS=$ac_cv_path_CUPS_PDFTOPS
+if test -n "$CUPS_PDFTOPS"; then
+  { echo "$as_me:$LINENO: result: $CUPS_PDFTOPS" >&5
+echo "${ECHO_T}$CUPS_PDFTOPS" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+	if test "x$CUPS_PDFTOPS" != x; then
+		cat >>confdefs.h <<\_ACEOF
+#define HAVE_PDFTOPS 1
+_ACEOF
+
+		PDFTOPS="pdftops"
+	else
+		{ { echo "$as_me:$LINENO: error: Unable to find pdftops program!" >&5
+echo "$as_me: error: Unable to find pdftops program!" >&2;}
+   { (exit 1); exit 1; }; }
+		exit 1
+	fi
+	;;
+esac
+
+cat >>confdefs.h <<_ACEOF
+#define CUPS_PDFTOPS "$CUPS_PDFTOPS"
+_ACEOF
+
+cat >>confdefs.h <<_ACEOF
+#define CUPS_GHOSTSCRIPT "$CUPS_GHOSTSCRIPT"
+_ACEOF
 
 
 
@@ -19731,6 +20084,8 @@ CUPS_SNMP_ADDRESS!$CUPS_SNMP_ADDRESS$ac_delim
 CUPS_SNMP_COMMUNITY!$CUPS_SNMP_COMMUNITY$ac_delim
 DEFAULT_IPP_PORT!$DEFAULT_IPP_PORT$ac_delim
 PAP!$PAP$ac_delim
+CUPS_PDFTOPS!$CUPS_PDFTOPS$ac_delim
+CUPS_GHOSTSCRIPT!$CUPS_GHOSTSCRIPT$ac_delim
 PDFTOPS!$PDFTOPS$ac_delim
 JAVA!$JAVA$ac_delim
 PERL!$PERL$ac_delim
@@ -19738,8 +20093,6 @@ PHP!$PHP$ac_delim
 PHPCONFIG!$PHPCONFIG$ac_delim
 PHPDIR!$PHPDIR$ac_delim
 PYTHON!$PYTHON$ac_delim
-INSTALL_LANGUAGES!$INSTALL_LANGUAGES$ac_delim
-UNINSTALL_LANGUAGES!$UNINSTALL_LANGUAGES$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -19781,11 +20134,13 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+INSTALL_LANGUAGES!$INSTALL_LANGUAGES$ac_delim
+UNINSTALL_LANGUAGES!$UNINSTALL_LANGUAGES$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 2; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 4; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
