2.3.0-5 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/tests/utils/test-drivers b/debian/tests/utils/test-drivers
--- a/debian/tests/utils/test-drivers
+++ b/debian/tests/utils/test-drivers
@@ -59,8 +59,20 @@ for driver in $DRIVERS_LIST; do
         rid=$(/usr/bin/lp -d $DUMMY_PRINTER_NAME $file | sed -e 's/^.*request id is \(.*\) (.*)$/\1/g')
     
         # Wait for the print to finish
-        while /usr/bin/lpstat | grep -q "^$rid "; do
+        while LPSTAT=`LANG=C /usr/bin/lpstat -l` && echo $LPSTAT | grep -q "^$rid "; do
             /bin/sleep 1s
+            echo -n "."
+            # If the filter is failed; stop the waiting and give as much context as possible
+            if echo $LPSTAT | grep -A3 "^$rid" | grep -q "Filter failed"; then
+                echo " Filter failed, aborting!"
+                >&2 echo "$ lpstat -l"
+                >&2 echo "$LPSTAT"
+                # Get job-id from request-id; assume it's ${printer_name}-${job_id}
+                jobid=$(echo $rid | sed -e "s/^${DUMMY_PRINTER_NAME}-//g")
+                >&2 echo "$ grep "\[Job $jobid\]" /var/log/cups/error_log"
+                >&2 grep "\[Job $jobid\]" /var/log/cups/error_log
+            break
+            fi
             echo -n "."
         done
         echo " done."
